### ISSUE TITLE
Silent installation with one command

### ISSUE THREAD

**Issue by winexec** [JackieDo/Xampp-vHosts-Manager#2]
Hi,

its possible to add some type of silent installation with one command?
Then flush dns ( ipconfig /flushdns )  and restart apache.

`xvhost silent-new domain.com|c:\xampp\htdocs\domain.com|admin@domain.com|ssl[0,1]`

Thanks for a great tool :)

**Comment by JackieDo** [comment]
@winexec : Thank you for your compliment. Initially, I built this library for the following purposes:
- Addressing needs for my students.
- Prove to my students that it is still possible to create a command-line application regardless of the language or support library.

In fact, such an existing construction is not highly effective. The use of libraries that have been painstakingly built to coordinate the package is a must. For example, instead of rewriting the console features, we should apply the `Symfony/Console` library, the effect will be higher.

So I will proceed to rebuild this library in the future after I finish all my unfinished projects. Hope you spend some time evaluating it then.
