### ISSUE TITLE
icacls

### ISSUE THREAD

**Issue by silaswint** [JackieDo/Xampp-vHosts-Manager#3]
on install.php it needs to be 

icacls C:\Windows\System32\drivers\etc\hosts /grant "Benutzer":MRXRW

instead of

icacls C:\Windows\System32\drivers\etc\hosts /grant "User":MRXRW

Maybe there should be a asking for the current language or something like that. "User" makes it doesn't work on my pc

**Comment by JackieDo** [comment]
To @silaswint:

Thank you for reporting this issue to me. This bugs actually arises due to the language compatibility problem of the operating system. When I first built this project, I didn't anticipate this problem. Therefore, my command line `icacls` is only compatible if the operating system uses English.

In fact, that "icacls" statement should be like this:
```
icacls C:\Windows\System32\drivers\etc\hosts /grant "*S-1-5-32-545":MRXRW
```
>Note: `*S-1-5-32-545` is Well-known SID for the `Users` account, regardless of what language the OS is using. See [here](https://docs.microsoft.com/vi-vn/windows/win32/secauthz/well-known-sids) for more details.

I released a new version, refactored the source code and fixed this bug. See how to update your XVHM [here](https://github.com/JackieDo/Xampp-vHosts-Manager#updation).
