### ISSUE TITLE
Creates vhosts but dont add a the host to the windows hosts file 

### ISSUE THREAD

**Issue by mrelliot69** [JackieDo/Xampp-vHosts-Manager#4]
Creates vhosts but dont add a the host to the windows hosts file . Is this feature enable or is not possible do do this auto?

**Comment by JackieDo** [comment]
To @mrelliot69 :

Adding the hostname to the `Windows hosts` file is completely automatic every time you create a new virtual host. Your issue exists because the `Windows hosts` file is not granted the necessary permissions. This is a bug mentioned in issue #3. I fixed this and released a new version.

You can solve your problem in one of two ways:

**Manually (if you don't want to upgrade core)**:
You manually grant "Modify, Read & execute, Read, Write" permissions to the `Windows hosts` file for the `Users` account.

**Automatically (if you want to upgrade to latest released version)**:
- Carefully upgrade your XVHM according to the instructions [here](https://github.com/JackieDo/Xampp-vHosts-Manager#updation).
- Run the command `xvhost grantperms_winhosts` to grant necessary permissions to the `Windows hosts` file.

Best regards.
